---
- name: Install dependencies
  hosts: all
  become: yes
  tasks:
    - name: Fetch node setup script
      get_url:
        url: https://deb.nodesource.com/setup_10.x
        dest: /etc/node10_setup.sh
    - name: Update repositories
      command: bash /etc/node10_setup.sh
    - name: Install node and npm
      apt: pkg=nodejs state=present
    - name: Install rsync
      apt: pkg=rsync state=present

- name: Create serving directory
  hosts: all
  become: yes
  tasks:
    - name: Create directory
      file:
        owner: vagrant
        path: "{{ lookup('env', 'DEPLOY_PATH') }}"
        state: directory
